name: Test GGUF Conversion Tool

on:
  workflow_dispatch:

jobs:
  test-convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # fallback if requirements.txt not present
          pip install huggingface-hub  # used by convert.py

      - name: Download llama.cpp prebuilt binaries
        run: |
          mkdir -p llama-bin
          curl -L -o llama.zip https://github.com/ggml-org/llama.cpp/releases/download/b6106/llama-b6106-bin-ubuntu-x64.zip
          unzip llama.zip -d llama-bin

      - name: Add llama binaries to PATH
        run: echo "${{ github.workspace }}/llama-bin/build/bin" >> $GITHUB_PATH

      - name: Download convert.py
        run: |
          mkdir -p scripts
          curl -L -o scripts/convert.py https://raw.githubusercontent.com/ggml-org/llama.cpp/master/scripts/convert.py
      
      - name: Dry-run convert.py with fake paths
        run: |
          echo "Running convert.py with fake paths for dry-run sanity check"
          python scripts/convert.py \
            --outfile test.gguf \
            --config config.json \
            --checkpoint model/model.bin || echo "Expected failure: ok"

