name: Llama-4 Scout Inference

on:
  workflow_dispatch:

permissions:
  models: read  # required to use GitHub Models API

jobs:
  llama4-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Run inference with Llama-4 Scout
        run: |
          echo "Sending prompt to Llama-4 Scout 17B..."
          curl -s https://models.github.ai/inference/chat/completions \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "azureml-meta/Llama-4-Scout-17B-16E-Instruct",
              "messages": [
                {"role": "user", "content": "Summarize the benefits of using GitHub Models in CI workflows."}
              ],
              "temperature": 0.7,
              "max_tokens": 300
            }' | jq
