name: Run GPT Model on macOS with Prepackaged Weights

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: macos-15  # Apple Silicon (M1/M2)

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: pip install 'huggingface_hub[cli]'

      - name: Clone gpt-oss repository
        run: git clone https://github.com/openai/gpt-oss.git

      - name: Install gpt-oss with Metal backend
        run: |
          cd gpt-oss
          pip install .[metal]
          cd ..

      - name: Download and extract GPT-OSS Metal weights from latest release
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            REPO: ${{ github.repository }}
          run: |
            mkdir -p gpt-oss-20b
            gh release download --repo "$REPO" --pattern "gpt-oss-20b-metal.tar.gz"
            tar -xzf gpt-oss-20b-metal.tar.gz -C gpt-oss-20b
            ls -lh gpt-oss-20b/metal/model.bin

        - name: Run GPT-OSS-20B with Metal backend
          run: |
            cd gpt-oss
            python - <<EOF
            from gpt_oss.metal.examples.generate import main
            main('../gpt-oss-20b/metal/model.bin', prompt="Hello from GitHub Actions!")
            EOF
