name: Llama 3 Inference

on:
  workflow_dispatch:

permissions:
  models: read

jobs:
  inference:
    runs-on: ubuntu-latest
    steps:
      - name: Call Llama 3.3-70B-Instruct via GitHub Models
        run: |
          curl -s https://models.github.ai/inference/chat/completions \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/json" \
            -d "$(cat <<EOF
              {
                "model": "Llama-3.3-70B-Instruct",
                "messages": [
                  {
                    "role": "user",
                    "content": "Explain the benefits of GitHub Models for CI workflows."
                  }
                ],
                "temperature": 0.7,
                "max_tokens": 300
              }
              EOF
              )" | jq
