name: Convert Model to .task Bundle

on: workflow_dispatch

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mediapipe torch  # Add others as needed

      - name: Download model.bin and tokenizer
        run: |
          mkdir model && cd model
          curl -L -o model.bin https://huggingface.co/openai/gpt-oss-20b/resolve/main/metal/model.bin
          curl -L -o tokenizer.model https://huggingface.co/path/to/tokenizer.model

      - name: Convert to TFLite with AI Edge Torch
        run: |
          python - <<EOF
          from mediapipe.tasks.python.genai import converter
          from mediapipe.tasks.python.core import task_options
          config = converter.ConversionConfig(
            tflite_model_path='model/model.tflite',
            base_model_path='model/model.bin',
            backend='cpu',
            # More ConversionConfig parameters as needed
          )
          converter.convert_checkpoint(config)
          EOF

      - name: Bundle into .task file
        run: |
          python - <<EOF
          import mediapipe as mp
          from mediapipe.tasks.python.genai import bundler
          config = bundler.BundleConfig(
            tflite_model='model/model.tflite',
            tokenizer_model='model/tokenizer.model',
            start_token='▁',
            stop_tokens=['▁</s>'],
            output_filename='model/model.task',
            enable_bytes_to_unicode_mapping=True,
          )
          bundler.create_bundle(config)
          EOF

      - name: Upload .task artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-model
          path: model/model.task